### ISSUE TITLE
Allow Hamlet to be recursively callable

### ISSUE THREAD

**Issue by sdemos** [yesodweb/shakespeare#157]
What I'm trying to do is to have essentially higher order widgets that can be called from whamlet templates. Essentially, it ends up being this - 

```
[whamlet|<div .row>
  ^{widgetFunction [whamlet|<strong>example title|] [whamlet|<p>example text]}
|]
```

Except put into an external file with `whamletFile`. (See [this gist](https://gist.github.com/sdemos/11d636bb848202b9e7ef) for a more complete example)

However, when I call the whamlet QQ inside of the widget embedding block (`^{}`) the parser chokes on the `[` - 

```
    Exception when trying to run compile-time code:
unexpected "["
expecting "}"
```

It seems that the problem is only with the parser, because if I put the call to the widget function inside of a where clause and then embed the resulting widget, it works just fine. 

```
page = [whamlet|<div .row>
  ^{w}
|]
    where w = widgetFunction [whamlet|<strong>example title|] [whamlet|<p>example text]
```

But this is an awkward workflow when the templates are defined in external files. 

Currently we are working around this issue by passing a string with HTML in it and calling `preEscapedText` on it before embedding the argument into the widget function. However, I would really like to be able to use various hamlet features on the HTML we are passing to the widget function, as well as being able to pass in the results of other widget functions. 

On the same note as this, it would be nice, for readability, to be able to have newlines between arguments inside of the `^{}` block. It seems that the parser chokes on `\n` the same way it does on `[`.

**Comment by snoyberg** [comment]
This is unlikely to happen, because of how the templating interacts with GHC. When you use `[whamlet|...|]`, you're creating compile-time code which GHC runs and then generates some new code. Doing this from inside of Hamlet would introduce some weird corner cases, and be very difficult to implement in the first place.

**Comment by sdemos** [comment]
That's unfortunate. It would have been a really cool feature for us. 

Out of curiosity, what kinds of corner cases would come up in my first example that wouldn't also come up in my second example? Also, why can't you just call the whamlet QQ again on any `[whamlet|...|]` code inside of a `^{}` block?

**Comment by snoyberg** [comment]
None of this is *impossible*, just very difficult, because we're talking about code vs code-that-generates-code. We'd need to handle parsing of quasiquoters, running TH code, splicing that back in, etc. There are possible complications with stage restrictions and the runtime linker getting confused.

**Comment by jezen** [comment]
This issue is inactive, so I'll close it for now.
