### ISSUE TITLE
Feature request: parent selector in Lucius templates

### ISSUE THREAD

**Issue by brandon-leapyear** [yesodweb/shakespeare#237]
It would be great to add the `&` LESS/SCSS parent selector ([LESS docs](http://lesscss.org/features/#parent-selectors-feature))

```less
p {
    &.foo { ... }
    &.bar { ... }
}
```

**Comment by jezen** [comment]
@brandon-leapyear Both Lucius and Cassius templates support this feature. My team uses it extensively.

I'll close this issue because it's old and the feature works, but if there is some specific context that the feature isn't working in (and ideally, you could provide us with an example), then please do open another issue.

**Comment by brandon-leapyear** [comment]
Sounds good. We moved off of Yesod soon after I opened this ticket, so I have no experience with newer features
